name: Debug workflow

on:
  pull_request:
    types: [labeled]

jobs:
  job1:
    name: Debug job
    # if: github.event.label.name == 'question'
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        uses: crazy-max/ghaction-dump-context@v2
      - name: Hello
        run: bash ./.github/run.sh
      # - name: 'Post Comment (End)'
      #   uses: actions/github-script@v4
      #   env:
      #     MESSAGE: |
      #       Job finished
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: process.env.MESSAGE
      #       })
